// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRhImQw_S2YGWG66w_F_rhlJLLbMsnPjo',
    appId: '1:508235811266:web:aa94975cace4e7ec86ee5b',
    messagingSenderId: '508235811266',
    projectId: 'fir-flutter-codelab-d17c2',
    authDomain: 'fir-flutter-codelab-d17c2.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-d17c2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHTAXWjl8NIywYihDVBvDoR7Ypw94iFX8',
    appId: '1:508235811266:android:556e11a39b45cc1986ee5b',
    messagingSenderId: '508235811266',
    projectId: 'fir-flutter-codelab-d17c2',
    storageBucket: 'fir-flutter-codelab-d17c2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeliM5CcZ3P8ktNSPWNz76s965h39SCkY',
    appId: '1:508235811266:ios:45d717a21f67542986ee5b',
    messagingSenderId: '508235811266',
    projectId: 'fir-flutter-codelab-d17c2',
    storageBucket: 'fir-flutter-codelab-d17c2.appspot.com',
    iosClientId: '508235811266-b4b5rqjm6l1e9uhj44vgb8m7ifm5ca06.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeliM5CcZ3P8ktNSPWNz76s965h39SCkY',
    appId: '1:508235811266:ios:45d717a21f67542986ee5b',
    messagingSenderId: '508235811266',
    projectId: 'fir-flutter-codelab-d17c2',
    storageBucket: 'fir-flutter-codelab-d17c2.appspot.com',
    iosClientId: '508235811266-b4b5rqjm6l1e9uhj44vgb8m7ifm5ca06.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
